# Perform simple package update/install tasks
---
- name: Update servers
  hosts: all
  gather_facts: no

  tasks:
    - name: Run apt update
      apt: update_cache=yes

    - name: Install required packages
      apt: name={{ item }} state=present
      with_items:
        - php
        - sudo
        - python-pip
        - inotify-tools

    - name: Install with pip, force upgrade
      pip: 
        name: psutil
        extra_args: --upgrade